// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sxvharmiyhmqsfxylbth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4dmhhcm1peWhtcXNmeHlsYnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NjI2MDgsImV4cCI6MjA3OTAzODYwOH0.Ybz-d6glupqle5xjYJPlitPoKpqC94EPSA3PllVTNzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);